---
Name: gridsheet-config
---
Injector:
  GridSheetAddNewComponent: GridSheetAddNewInlineButton
  GridSheetEditableColumnComponent: GridSheetEditableColumns
  GridField: GridSheet
  GridFieldDetailForm: GridSheetDetailForm
  GridFieldDetailForm_ItemRequest: GridSheetDetailForm_ItemRequest
GridSheetModelExtension:
  default_field_specs:
    Title:
      title: 'Title'
      field: 'TextField'
ModelAdmin:
  extensions:
    - GridSheetModelAdminExtension