---
Name: gridsheet-config
After:
  - 'framework/*'
  - 'cms/*'
---
Injector:
  GridSheetAddNewComponent:
    class: GridSheetAddNewInlineButton
  GridSheetEditableColumnsComponent:
    class: GridSheetEditableColumnsComponent
  GridField:
    class: GridSheet
  GridFieldDetailForm:
    class: GridSheetDetailForm
  GridFieldDetailForm_ItemRequest:
    class: GridSheetDetailForm_ItemRequest
GridSheetModelExtension:
  default_field_specs:
    Title:
      title: 'Title'
      field: 'TextField'
ModelAdmin:
  extensions:
    - GridSheetModelAdminExtension